// <auto-generated />
namespace OborudDataBase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _24_09 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_24_09));
        
        string IMigrationMetadata.Id
        {
            get { return "202009241245112_24_09"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
